logger:
  name: app
  path: app.log
  fmt: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  datefmt: "%Y-%m-%d %H:%M:%S"

plotter:
  path: output_plot.png


Quadrotor:
  xml_body_name: x2
  cda: 0.04

MovingPlatform:
  xml_body_name: platform_body
  cda: 0.25
  radius: 1
  locks_arms_length: 0.03


Follow_Orch:
  viewer:
    camera_distance_coef: 1.5
    camera_distance_ff: 5

  env:
    default_wind: [0, 0, 0]
    air_density: 1.225

Predictor:
  time_frame: 15
  detect_per_time_frame: 10
  tol_std: 0.2

Detector:
  px_to_meter: 0.03448275862

QuadrotorController:
  descend:
    ff_z: 0.02
    pids_z_upper_limit: 0.1
    pids_z_lower_limit: -0.2

  pids:
    x:
      ki: 0.15
      kd: 0.4
      setpoint: 0
      output_limit: 0.03
    y:
      ki: 0.15
      kd: 0.4
      setpoint: 0
      output_limit: 0.03
    z:
      ki: 0.15
      kd: 0.55
      setpoint: 1
      output_limit: 0.8
    ro:
      ki: 0.50
      kd: 0.30
      setpoint: 0
      output_limit: 0.05
    pi:
      ki: 0.50
      kd: 0.20
      setpoint: 0
      output_limit: 0.05
    ya:
      ki: 0.50
      kd: 0.50
      setpoint: 0
      output_limit: 2

  ff:
    x: 1.74
    y: 1.74
    z: 5
    throttle: 3.2495625



camera_streamer:
  fps: 60
  width: 320
  height: 240