path_to_xml: "skydio_x2/scene.xml"

logger:
  name: app
  path: app.log
  fmt: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"

plotter:
  path: output_plot.png


Quadrotor:
  xml_body_name: Quadrotor
  cda: 0.04
  sensors:
    framepos: Quadrotor_framepos
    rangefinder: Quadrotor_rangefinder


Pad:
  xml_body_name: Pad
  cda: 0.25
  sensors:
    framepos: Pad_framepos
  radius: 1
  locks_arms_length: 0.03
  default_velocity: [0, 0, 0]


Follow_Orch:
  viewer:
    camera_distance_coef: 1.5
    camera_distance_ff: 8
  env:
    default_wind: [0, 0, 0]
    air_density: 1.225

Predictor:

Detector:
  history_max_len: 200
  tol_stddev: 0.1
  px_to_meter: 0.03448275862

QuadrotorController:
  descend_phases:
    names: ['fast-drop', 'approach', 'touchdown']
    ff_z:     [3, 0.5, 0.02]
    pid_z_ul: [0.1, 0.1, 0.1]
    pid_z_ll: [-0.1, -0.05, -0.005]

  pids:
    x:
      kp: 0.15
      kd: 0.4
      setpoint: 0
      output_limit: 0.03
    y:
      kp: 0.15
      kd: 0.4
      setpoint: 0
      output_limit: 0.03
    z:
      kp: 0.15
      kd: 0.60
      setpoint: 0
      output_limit: 0.8
    ro:
      kp: 0.50
      kd: 0.30
      setpoint: 0
      output_limit: 0.05
    pi:
      kp: 0.50
      kd: 0.20
      setpoint: 0
      output_limit: 0.05
    ya:
      kp: 0.50
      kd: 0.50
      setpoint: 0
      output_limit: 2

  ff:
    x: 1.74
    y: 1.74
    z: 10
    throttle: 3.2495625


  mixing-matrix:
    [
      [ 1, 1, 1, 1 ],
      [ 1, -1, 1, -1 ],
      [ 1, -1, -1, 1 ],
      [ 1, 1, -1, -1 ]
    ]




camera_streamer:
  fps: 60
  width: 320
  height: 240